### PR TITLE
Add sqe consts 

### PR DESCRIPTION
**Pull request by twissel**
Define "sqe constants" in uring-sys, rather than in iou

### CODE REVIEW

**Comment by withoutboats** [comment]
There are several other constants defined in liburing, which weren't defined in iou because they weren't used there. But uring-sys should expose all of them :)

You can find them at in the liburing git repository at `src/include/liburing/io_uring.h` https://git.kernel.dk/cgit/liburing/tree/src/include/liburing/io_uring.h#n60

**Comment by twissel** [comment]
Yes, i was thinking about this, will add

**Comment by twissel** [comment]
done

**Comment by withoutboats** [comment]
Thanks!

**Pull request merged**
